// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqz-TsXXaf0JFX0on2GlneVxz7Acq7ZKE',
    appId: '1:390128912429:android:3add2f12fb3b498fc3d0a4',
    messagingSenderId: '390128912429',
    projectId: 'propertier-6291b',
    storageBucket: 'propertier-6291b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4i_F-fgcIUyGSvSUAJ7wMjiittKmvxeY',
    appId: '1:390128912429:ios:9bfa8a4ff07c228ac3d0a4',
    messagingSenderId: '390128912429',
    projectId: 'propertier-6291b',
    storageBucket: 'propertier-6291b.appspot.com',
    androidClientId: '390128912429-005neutng70hdt8edaq3hogdv7vim30o.apps.googleusercontent.com',
    iosClientId: '390128912429-dvc8rre8gelfo18nao51ktkpff3ni0vq.apps.googleusercontent.com',
    iosBundleId: 'com.propertier.propertiercom',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5aymyrfobnLDusSVYw0Lqaqu7_KTEKkA',
    appId: '1:390128912429:web:d013a0e4cff472a0c3d0a4',
    messagingSenderId: '390128912429',
    projectId: 'propertier-6291b',
    authDomain: 'propertier-6291b.firebaseapp.com',
    storageBucket: 'propertier-6291b.appspot.com',
    measurementId: 'G-V1QL4V1GBP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4i_F-fgcIUyGSvSUAJ7wMjiittKmvxeY',
    appId: '1:390128912429:ios:9bfa8a4ff07c228ac3d0a4',
    messagingSenderId: '390128912429',
    projectId: 'propertier-6291b',
    storageBucket: 'propertier-6291b.appspot.com',
    androidClientId: '390128912429-005neutng70hdt8edaq3hogdv7vim30o.apps.googleusercontent.com',
    iosClientId: '390128912429-dvc8rre8gelfo18nao51ktkpff3ni0vq.apps.googleusercontent.com',
    iosBundleId: 'com.propertier.propertiercom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5aymyrfobnLDusSVYw0Lqaqu7_KTEKkA',
    appId: '1:390128912429:web:f6f14e6068bb277bc3d0a4',
    messagingSenderId: '390128912429',
    projectId: 'propertier-6291b',
    authDomain: 'propertier-6291b.firebaseapp.com',
    storageBucket: 'propertier-6291b.appspot.com',
    measurementId: 'G-6FM2VBGYPD',
  );

}